In [1]:
import torchreid
model_name = 'resnet50'
dataset_name = 'market1501'
datamanager = torchreid.data.ImageDataManager(
    root="reid-data",
    sources=dataset_name,
    targets=dataset_name,
    height=256,
    width=128,
    batch_size_train=128,
    batch_size_test=100,
    transforms=["random_flip", "random_crop"]
)

/home/trewq/Desktop/Projects/RetailAnalytics/REID/RESEARCH/deep-person-reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(


Building train transforms ...
+ resize to 256x128
+ random flip
+ random crop (enlarge to 288x144 and crop 256x128)
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------
=> Loading test (target) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gal

In [8]:
train_loader = datamanager.train_loader
for batch_idx, data in enumerate(train_loader):
    print(data['pid'])
    break

tensor([373, 367, 515, 327,  30, 465, 416, 111, 230, 684,  33, 151, 556, 627,
        229, 373, 190, 198, 395, 386, 499, 722, 520, 398, 682, 440,  55, 653,
        243,  54,  70,  61, 398, 425, 284, 397, 484, 526,  45, 531, 132, 352,
        373, 507, 217, 327, 224,  30,  77, 136, 127, 528,  48, 409, 577, 385,
        486,  63, 315, 684, 421, 151,  54, 132, 579, 175, 421,  57, 554, 186,
        708, 666, 165,  48, 519,  16, 612, 416, 227, 201, 613, 314,  70, 314,
        694,  96, 591,  92, 201, 327, 696, 244, 593,  93, 369, 490, 316, 443,
        342, 496, 343, 676, 104, 601, 537,  64, 167, 105, 474, 585, 440,  26,
        522, 708, 446, 114,  61, 173, 171, 601, 425, 580, 709, 463, 577, 459,
        399, 369])


In [4]:
model = torchreid.models.build_model(
    name=model_name,
    num_classes=datamanager.num_train_pids, #2000 for Tango
    loss="triplet",
    pretrained=True,
    pooling='gem',
    custom_layers=['ArcFaceMarginProduct']
)
model = model.cuda()
optimizer = torchreid.optim.build_optimizer(
    model,
    optim="adam",
    lr=0.0003
)

scheduler = torchreid.optim.build_lr_scheduler(
    optimizer,
    lr_scheduler="single_step",
    stepsize=20
)

In [5]:
# from tools.visualize_actmap import visactmap
# test_loader = datamanager.test_loader
# visactmap(model, test_loader, f"log/visactmap_{model_name}_{dataset_name}", 128, 256, True, [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

In [7]:
engine = torchreid.engine.ImageSoftmaxEngine(
    datamanager,
    model,
    optimizer=optimizer,
    scheduler=scheduler,
    label_smooth=True
)

In [8]:
engine.run(
    save_dir=f"log/{model_name}_{dataset_name}",
    max_epoch=60,
    eval_freq=5,
    print_freq=50,
    test_only=False,
    visrank=False,
    eval_metric='default'
)

=> Start training


  0%|          | 0/60 [00:00<?, ?it/s]

epoch: [1/60][50/101]	time 0.153 (0.156)	data 0.002 (0.006)	eta 0:15:39	loss 5.1502 (5.1459)	acc 100.0000 (100.0000)	lr 0.000000


  2%|▏         | 1/60 [00:15<15:22, 15.64s/it]

epoch: [1/60][100/101]	time 0.152 (0.154)	data 0.002 (0.004)	eta 0:15:20	loss 5.1373 (5.1428)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [2/60][50/101]	time 0.153 (0.156)	data 0.002 (0.005)	eta 0:15:23	loss 5.1242 (5.1304)	acc 100.0000 (100.0000)	lr 0.000000


  3%|▎         | 2/60 [00:31<15:07, 15.65s/it]

epoch: [2/60][100/101]	time 0.153 (0.155)	data 0.001 (0.004)	eta 0:15:06	loss 5.1082 (5.1296)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [3/60][50/101]	time 0.153 (0.157)	data 0.002 (0.006)	eta 0:15:11	loss 5.1430 (5.1204)	acc 100.0000 (100.0000)	lr 0.000000


  5%|▌         | 3/60 [00:46<14:52, 15.66s/it]

epoch: [3/60][100/101]	time 0.152 (0.155)	data 0.001 (0.004)	eta 0:14:51	loss 5.1448 (5.1191)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [4/60][50/101]	time 0.152 (0.157)	data 0.002 (0.006)	eta 0:14:55	loss 5.1256 (5.1144)	acc 100.0000 (100.0000)	lr 0.000000


  7%|▋         | 4/60 [01:02<14:37, 15.66s/it]

epoch: [4/60][100/101]	time 0.152 (0.155)	data 0.002 (0.004)	eta 0:14:35	loss 5.0888 (5.1093)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [5/60][50/101]	time 0.152 (0.156)	data 0.002 (0.005)	eta 0:14:36	loss 5.1295 (5.0994)	acc 100.0000 (100.0000)	lr 0.000000


100%|██████████| 101/101 [00:15<00:00,  6.47it/s]


epoch: [5/60][100/101]	time 0.152 (0.154)	data 0.002 (0.004)	eta 0:14:17	loss 5.1207 (5.0994)	acc 100.0000 (100.0000)	lr 0.000000
##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.18it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 28.79it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0018 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 71.9%
CMC curve
Rank-1  : 88.6%
Rank-5  : 95.0%
Rank-10 : 96.5%
Rank-20 : 97.9%


  8%|▊         | 5/60 [01:57<27:12, 29.69s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-5"


epoch: [6/60][50/101]	time 0.153 (0.157)	data 0.002 (0.006)	eta 0:14:25	loss 5.0941 (5.0900)	acc 100.0000 (100.0000)	lr 0.000000


 10%|█         | 6/60 [02:12<22:25, 24.92s/it]

epoch: [6/60][100/101]	time 0.149 (0.155)	data 0.001 (0.004)	eta 0:14:03	loss 5.0798 (5.0893)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [7/60][50/101]	time 0.153 (0.156)	data 0.002 (0.005)	eta 0:14:02	loss 5.0592 (5.0857)	acc 100.0000 (100.0000)	lr 0.000000


 12%|█▏        | 7/60 [02:28<19:19, 21.88s/it]

epoch: [7/60][100/101]	time 0.152 (0.154)	data 0.002 (0.003)	eta 0:13:46	loss 5.0655 (5.0810)	acc 100.0000 (99.9922)	lr 0.000000


epoch: [8/60][50/101]	time 0.154 (0.157)	data 0.002 (0.005)	eta 0:13:52	loss 5.1255 (5.0736)	acc 100.0000 (100.0000)	lr 0.000000


 13%|█▎        | 8/60 [02:43<17:12, 19.85s/it]

epoch: [8/60][100/101]	time 0.148 (0.153)	data 0.002 (0.004)	eta 0:13:24	loss 5.0798 (5.0711)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [9/60][50/101]	time 0.147 (0.152)	data 0.002 (0.006)	eta 0:13:11	loss 5.0926 (5.0630)	acc 100.0000 (100.0000)	lr 0.000000


 15%|█▌        | 9/60 [02:59<15:38, 18.40s/it]

epoch: [9/60][100/101]	time 0.147 (0.150)	data 0.001 (0.004)	eta 0:12:53	loss 5.0588 (5.0609)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [10/60][50/101]	time 0.157 (0.154)	data 0.002 (0.005)	eta 0:13:05	loss 5.0251 (5.0542)	acc 100.0000 (100.0000)	lr 0.000000


100%|██████████| 101/101 [00:15<00:00,  6.54it/s]


epoch: [10/60][100/101]	time 0.147 (0.153)	data 0.001 (0.003)	eta 0:12:51	loss 5.0269 (5.0527)	acc 100.0000 (100.0000)	lr 0.000000
##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.84it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.99it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0018 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 71.8%
CMC curve
Rank-1  : 88.4%
Rank-5  : 95.0%
Rank-10 : 96.4%
Rank-20 : 97.8%


 17%|█▋        | 10/60 [03:53<24:33, 29.46s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-10"


epoch: [11/60][50/101]	time 0.153 (0.155)	data 0.002 (0.005)	eta 0:12:54	loss 5.0605 (5.0425)	acc 100.0000 (100.0000)	lr 0.000000


 18%|█▊        | 11/60 [04:08<20:34, 25.19s/it]

epoch: [11/60][100/101]	time 0.153 (0.153)	data 0.002 (0.004)	eta 0:12:38	loss 5.0440 (5.0425)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [12/60][50/101]	time 0.151 (0.155)	data 0.002 (0.005)	eta 0:12:39	loss 5.0338 (5.0403)	acc 100.0000 (100.0000)	lr 0.000000


 20%|██        | 12/60 [04:24<17:46, 22.21s/it]

epoch: [12/60][100/101]	time 0.147 (0.152)	data 0.002 (0.004)	eta 0:12:16	loss 5.0158 (5.0336)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [13/60][50/101]	time 0.154 (0.153)	data 0.002 (0.006)	eta 0:12:15	loss 5.0648 (5.0242)	acc 100.0000 (100.0000)	lr 0.000000


 22%|██▏       | 13/60 [04:39<15:45, 20.12s/it]

epoch: [13/60][100/101]	time 0.148 (0.151)	data 0.001 (0.004)	eta 0:11:57	loss 4.9968 (5.0251)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [14/60][50/101]	time 0.152 (0.154)	data 0.002 (0.005)	eta 0:12:02	loss 4.9474 (5.0195)	acc 100.0000 (100.0000)	lr 0.000000


 23%|██▎       | 14/60 [04:55<14:21, 18.72s/it]

epoch: [14/60][100/101]	time 0.151 (0.153)	data 0.001 (0.004)	eta 0:11:51	loss 5.0133 (5.0147)	acc 100.0000 (100.0000)	lr 0.000000


epoch: [15/60][50/101]	time 0.152 (0.157)	data 0.002 (0.005)	eta 0:11:59	loss 5.0528 (5.0111)	acc 100.0000 (100.0000)	lr 0.000000


100%|██████████| 101/101 [00:15<00:00,  6.50it/s]


epoch: [15/60][100/101]	time 0.150 (0.154)	data 0.002 (0.004)	eta 0:11:37	loss 4.9929 (5.0074)	acc 100.0000 (100.0000)	lr 0.000000
##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.83it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.33it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 71.7%
CMC curve
Rank-1  : 88.1%
Rank-5  : 95.1%
Rank-10 : 96.4%
Rank-20 : 97.7%


 25%|██▌       | 15/60 [05:50<22:15, 29.67s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-15"


epoch: [16/60][50/101]	time 0.152 (0.156)	data 0.002 (0.005)	eta 0:11:42	loss 5.0165 (5.0038)	acc 100.0000 (100.0000)	lr 0.000000


 25%|██▌       | 15/60 [05:59<17:59, 23.98s/it]


KeyboardInterrupt: 