In [1]:
import torchreid
model_name = 'resnet50'
dataset_name = 'market1501'
datamanager = torchreid.data.ImageDataManager(
    root="reid-data",
    sources=dataset_name,
    targets=dataset_name,
    height=256,
    width=128,
    batch_size_train=128,
    batch_size_test=100,
    transforms=["random_flip", "random_crop"]
)

/home/trewq/Desktop/Projects/RetailAnalytics/REID/RESEARCH/deep-person-reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(


Building train transforms ...
+ resize to 256x128
+ random flip
+ random crop (enlarge to 288x144 and crop 256x128)
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------
=> Loading test (target) dataset
=> Loaded Market1501
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gal

In [2]:
model = torchreid.models.build_model(
    name=model_name,
    num_classes=datamanager.num_train_pids, #2000 for Tango
    loss="triplet",
    pretrained=True,
    pooling='gem'
)
model = model.cuda()
optimizer = torchreid.optim.build_optimizer(
    model,
    optim="adam",
    lr=0.0003
)

scheduler = torchreid.optim.build_lr_scheduler(
    optimizer,
    lr_scheduler="single_step",
    stepsize=20
)

In [5]:
# from tools.visualize_actmap import visactmap
# test_loader = datamanager.test_loader
# visactmap(model, test_loader, f"log/visactmap_{model_name}_{dataset_name}", 128, 256, True, [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

In [3]:
engine = torchreid.engine.ImageTripletEngine(
    datamanager,
    model,
    optimizer=optimizer,
    scheduler=scheduler,
    label_smooth=True
)

In [4]:
engine.run(
    save_dir=f"log/{model_name}_{dataset_name}",
    max_epoch=60,
    eval_freq=5,
    print_freq=5000,
    test_only=False,
    visrank=False,
    eval_metric='default'
)

=> Start training


100%|██████████| 101/101 [00:16<00:00,  5.98it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 28.30it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 30.95it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0024 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 50.5%
CMC curve
Rank-1  : 71.8%
Rank-5  : 86.2%
Rank-10 : 90.8%
Rank-20 : 94.1%


  8%|▊         | 5/60 [02:06<28:30, 31.10s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-5"


100%|██████████| 101/101 [00:17<00:00,  5.84it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.88it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 30.26it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 54.5%
CMC curve
Rank-1  : 75.4%
Rank-5  : 88.5%
Rank-10 : 92.6%
Rank-20 : 95.2%


 17%|█▋        | 10/60 [04:10<25:53, 31.07s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-10"


100%|██████████| 101/101 [00:16<00:00,  6.12it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 28.38it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 31.17it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 59.8%
CMC curve
Rank-1  : 79.8%
Rank-5  : 91.4%
Rank-10 : 94.4%
Rank-20 : 96.5%


 25%|██▌       | 15/60 [06:11<22:49, 30.43s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-15"


100%|██████████| 101/101 [00:16<00:00,  6.06it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 28.12it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 31.18it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 61.6%
CMC curve
Rank-1  : 81.5%
Rank-5  : 91.9%
Rank-10 : 94.5%
Rank-20 : 96.7%


 33%|███▎      | 20/60 [08:13<20:18, 30.46s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-20"


100%|██████████| 101/101 [00:17<00:00,  5.77it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 27.24it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.74it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0018 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 69.3%
CMC curve
Rank-1  : 86.2%
Rank-5  : 94.4%
Rank-10 : 96.4%
Rank-20 : 97.8%


 42%|████▏     | 25/60 [10:18<18:11, 31.20s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-25"


100%|██████████| 101/101 [00:17<00:00,  5.70it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.30it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.76it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 70.6%
CMC curve
Rank-1  : 87.0%
Rank-5  : 94.6%
Rank-10 : 96.9%
Rank-20 : 97.8%


 50%|█████     | 30/60 [12:25<15:49, 31.65s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-30"


100%|██████████| 101/101 [00:17<00:00,  5.72it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.93it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.53it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0020 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 70.9%
CMC curve
Rank-1  : 87.4%
Rank-5  : 94.9%
Rank-10 : 96.8%
Rank-20 : 97.8%


 58%|█████▊    | 35/60 [14:32<13:10, 31.60s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-35"


100%|██████████| 101/101 [00:17<00:00,  5.78it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 27.31it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.86it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 71.9%
CMC curve
Rank-1  : 87.9%
Rank-5  : 95.1%
Rank-10 : 96.7%
Rank-20 : 98.0%


 67%|██████▋   | 40/60 [16:39<10:32, 31.60s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-40"


100%|██████████| 101/101 [00:17<00:00,  5.73it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 27.42it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.77it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0018 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 71.9%
CMC curve
Rank-1  : 88.1%
Rank-5  : 95.0%
Rank-10 : 96.7%
Rank-20 : 97.9%


 75%|███████▌  | 45/60 [18:46<07:54, 31.61s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-45"


100%|██████████| 101/101 [00:17<00:00,  5.68it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 25.05it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.78it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 72.0%
CMC curve
Rank-1  : 88.1%
Rank-5  : 95.0%
Rank-10 : 96.7%
Rank-20 : 98.0%


 83%|████████▎ | 50/60 [20:54<05:16, 31.68s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-50"


100%|██████████| 101/101 [00:17<00:00,  5.72it/s]


##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 26.82it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.77it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0019 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 72.1%
CMC curve
Rank-1  : 87.9%
Rank-5  : 95.2%
Rank-10 : 96.6%
Rank-20 : 98.0%


 92%|█████████▏| 55/60 [23:00<02:37, 31.53s/it]

Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-55"


100%|██████████| 60/60 [24:29<00:00, 24.49s/it]


=> Final test
##### Evaluating market1501 (source) #####
Extracting features from query set ...


100%|██████████| 34/34 [00:01<00:00, 27.39it/s]


Done, obtained 3368-by-2048 matrix
Extracting features from gallery set ...


100%|██████████| 160/160 [00:05<00:00, 29.79it/s]


Done, obtained 15913-by-2048 matrix
Speed: 0.0018 sec/batch
Computing distance matrix with metric=euclidean ...
Computing CMC and mAP ...
[   0  455    0 ... 1026  668  723] <class 'numpy.ndarray'> False
** Results **
mAP: 72.2%
CMC curve
Rank-1  : 88.0%
Rank-5  : 95.0%
Rank-10 : 96.8%
Rank-20 : 97.9%
Checkpoint saved to "log/resnet50_market1501/model/model.pth.tar-60"
Elapsed 0:25:08
